export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEMS_LOADING = "ITEMS_LOADING";

export const GET_DEPARTAMENTOS = "GET_DEPARTAMENTOS";
export const GET_PROVINCIAS = "GET_PROVINCIAS";
export const GET_DISTRITOS = "GET_DISTRITOS";

export const GET_CURSOS = "GET_CURSOS";
export const GET_LICENCIAS = "GET_LICENCIAS";
export const ADD_FICHA_INSCRIPCION = "ADD_FICHA_INSCRIPCION";
export const GET_ESTADO = "GET_ESTADO";

export const GET_ALUMNOS_EN_PROCESO = "GET_ALUMNOS_EN_PROCESO";
export const MARCAR_ASISTENCIA = "MARCAR_ASISTENCIA";

// Expedientes
export const GET_EXPEDIENTE = "GET_EXPEDIENTE";
export const GET_EXPEDIENTES = "GET_EXPEDIENTES";

export const CHANGE_STATE_TOAST = "CHANGE_STATE_TOAST";

export const CHANGE_LIST_A = "CHANGE_LIST_A";
export const CHANGE_LIST_DE = "CHANGE_LIST_DE";
export const GET_CURSOS_LICENCIAS = "GET_CURSOS_LICENCIAS";

export const GET_HISTORIAL_EXTERNO = "GET_HISTORIAL_EXTERNO";
export const GET_ALUMNOS_DETALLADOS = "GET_ALUMNOS_DETALLADOS";
export const ADD_HISTORIAL_EXTERNO = "ADD_HISTORIAL_EXTERNO";
export const CHANGE_HISTORIAL_EXTERNO = "CHANGE_HISTORIAL_EXTERNO";
export const DELETE_HISTORIAL_EXTERNO = "DELETE_HISTORIAL_EXTERNO";

// Tramitadores
export const GET_TRAMITADORES = "GET_TRAMITADORES";

// Alumnos
export const GET_ALUMNOS = "GET_ALUMNOS";

// Vehiculos
export const GET_VEHICULOS = "GET_VEHICULOS";

// Instructores
export const GET_INSTRUCTORES = "GET_INSTRUCTORES";
